apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tsymbiote-mutating-webhook-configuration
webhooks:
- name: tsymbiote-adapter.kb.io
  namespaceSelector:
    matchExpressions:
      - key: tsymbiote-secret-injection
        operator: In
        values:
        - enabled
  objectSelector:
    matchLabels:
      tsymbiote-secret-injection: enabled