apiVersion: tsymbiote.dhouti.dev/v1alpha1
kind: TSymbiote
metadata:
  labels:
    app.kubernetes.io/name: tsymbiote
    app.kubernetes.io/managed-by: kustomize
  name: tsymbiote-sample
spec:
  # TODO(user): Add fields here
